- type: job
  id: HeadOfPrison
  name: job-name-head-of-prison
  description: job-description-head-of-prison
  playTimeTracker: JobHeadOfPrison
  requirements:
  - !type:RoleTimeRequirement
    role: JobHeadOfSecurity
    time: 36000 #10 hrs # Sunrise-RoleTime
  - !type:DepartmentTimeRequirement
    department: Security
    time: 108000 #30 hrs # Sunrise-RoleTime
  weight: 10
  startingGear: HeadOfPrisonGear
  icon: "JobIconHeadOfPrison"
  overrideConsoleVisibility: false
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  alwaysUseSpawner: true
  radioBold: true
  displayWeight: 100
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: HeadOfPrisonGear
  equipment:
    id: HeadOfPrisonPDA
    jumpsuit: ClothingUniformJumpsuitHoSOld
    head: ClothingHeadHatBeretHoS
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltPrisonGuardianFilled
    neck: ClothingNeckCloakHOSCloak
    pocket1: WeaponPistolDeagle
    pocket2: MagazineDeagle
    outerClothing: ClothingOuterArmorRiot
  storage:
    belt:
      - RadioHandheldSecurity
      - Flash

- type: chameleonOutfit
  id: HeadOfPrisonChameleonOutfit
  job: HeadOfPrison
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSGrey
