- type: job
  id: PrisonWorker
  name: job-name-prison-worker
  description: job-description-prison-worker
  playTimeTracker: JobPrisonWorker
  startingGear: PrisonWorkerGear
  icon: "JobIconPrisonWorker"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-head-of-prison
  alwaysUseSpawner: true
  canBeAntag: false
  displayWeight: 40
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Service
  - Chemistry
  - Medical
  - Engineering
  - Atmospherics
  - Janitor
  - Bar
  - Hydroponics
  - Kitchen
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PrisonWorkerGear
  equipment:
    id: PrisonWorkerPDA
    jumpsuit: ClothingUniformJumpsuitSecSummer
    head: ClothingHeadHatBeretSecurity
    ears: ClothingHeadsetService
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    belt: WeaponDisabler
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesBootsJack
    pocket1: Flash
    pocket2: SecurityWhistle
  storage:
    back:
      - Stunbaton
      - RadioHandheldSecurity
      - Handcuffs
      - GrenadeFlashBang
      - FlashlightSeclite

- type: chameleonOutfit
  id: PrisonWorkerChameleonOutfit
  job: PrisonWorker
  equipment:
    mask: ClothingMaskBreath