- type: job
  id: PrisonEngineer
  name: job-name-prison-engineer
  description: job-description-prison-engineer
  playTimeTracker: JobPrisonEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 7200 # 2 hrs
  alwaysUseSpawner: true
  canBeAntag: false
  startingGear: PrisonEngineerGear
  icon: "JobIconPrisonEngineer"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-head-of-prison
  displayWeight: 70
  access:
  - Security
  - Brig
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PrisonEngineerGear
  equipment:
    id: PrisonEngineerPDA
    jumpsuit: ClothingUniformJumpsuitEngineering
    head: ClothingHeadHatBeretEngineering
    ears: ClothingHeadsetJEngineering
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    belt: ClothingBeltUtilityEngineering
    back: ClothingBackpackEngineering
    shoes: ClothingShoesBootsJack
    pocket1: SecurityWhistle
    pocket2: WeaponDisabler
  storage:
    back:
      - Stunbaton
      - RadioHandheldSecurity
      - Flash
      - GrenadeFlashBang
      - Handcuffs
      - FlashlightSeclite

- type: chameleonOutfit
  id: PrisonEngineerChameleonOutfit
  job: PrisonEngineer