- type: job
  id: PrisonDoctor
  name: job-name-prison-doctor
  description: job-description-prison-doctor
  playTimeTracker: JobPrisonDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 # 2 hrs
  alwaysUseSpawner: true
  canBeAntag: false
  startingGear: PrisonDoctorGear
  icon: "JobIconPrisonDoctor"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-head-of-prison
  displayWeight: 60
  access:
  - Security
  - Brig
  - Maintenance
  - Medical
  - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PrisonDoctorGear
  equipment:
    id: PrisonDoctorPDA
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    head: ClothingHeadHatCapCMO
    ears: ClothingHeadsetMedical
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorRiot
    belt: ClothingBeltMedicalFilled
    back: ClothingBackpackMedical
    shoes: ClothingShoesBootsJack
    pocket1: SecurityWhistle
    pocket2: WeaponDisabler
  storage:
    back:
      - Stunbaton
      - RadioHandheldSecurity
      - Flash
      - GrenadeFlashBang
      - Handcuffs
      - FlashlightSeclite

- type: chameleonOutfit
  id: PrisonDoctorChameleonOutfit
  job: PrisonDoctor
